---
# role: sssd
# file: requirements.yml

roles:
  - name: jomrr.krb5
    src: https://github.com/jomrr/ansible-role-krb5.git
    scm: git
    version: main
  - name: jomrr.pam
    src: https://github.com/jomrr/ansible-role-pam.git
    scm: git
    version: main
