---
# role: sssd
# file: tasks/configure.yml

- name: SSSD | Create SSSD configuration directories
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ __sssd_directory }}"
    state: directory
    owner: root
    group: "{{ __sssd_config_group }}"
    mode: '0750'
  loop:
    - /etc/sssd
    - /etc/sssd/conf.d
  loop_control:
    loop_var: __sssd_directory
    label: "{{ __sssd_directory }}"

- name: SSSD | Configure and validate SSSD
  become: true
  become_user: root
  ansible.builtin.template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: "{{ __sssd_config_group }}"
    mode: '0640'
    backup: true
    validate: "{{ __sssd_validate }}"
  no_log: "{{ sssd_config_no_log }}"
  notify: restart sssd
