---
# role: samba_ad_sssd
# file: tasks/pam_RedHat.yml

- name: SAMBA_AD_SSSD | Read the native authentication profile
  become: true
  become_user: root
  ansible.builtin.command: authselect current --raw
  register: __samba_ad_sssd_authselect
  changed_when: false
  failed_when: __samba_ad_sssd_authselect.rc not in [0, 2]
  check_mode: false

- name: SAMBA_AD_SSSD | Select the SSSD authentication profile
  become: true
  become_user: root
  ansible.builtin.command:
    argv: >-
      {{ ['authselect', 'select'] + __samba_ad_sssd_authselect_profile +
         (samba_ad_sssd_authselect_force | ternary(['--force'], [])) }}
  changed_when: true
  when: __samba_ad_sssd_authselect.stdout.split() | sort != __samba_ad_sssd_authselect_profile | sort
