---
# role: sssd
# file: molecule/default/molecule.yml

dependency:
  name: "galaxy"
  options:
    requirements-file: "${MOLECULE_PROJECT_DIRECTORY}/collections.yml"
    role-file: "${MOLECULE_PROJECT_DIRECTORY}/requirements.yml"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 8
      interpreter_python: "auto_silent"
      callbacks_enabled: "ansible.builtin.default"
      callback_result_format: "yaml"
    connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        ansible_podman_mount_detection: false
        sssd_id_mapping: "rfc2307"
        sssd_keytab: "/etc/krb5.keytab"
        sssd_realm: "AD.SSSD.TEST"
        sssd_server: "dc-sssd.ad.sssd.test"
        sssd_join_password: "Molecule-Only-Adm1n!"
        __sssd_test_password: "Molecule-Only-Us3r!"
        sssd_host_fqdn: "{{ inventory_hostname }}.ad.sssd.test"
        pam_authselect_force: true
        sssd_domain_options:
          access_provider: "ad"
          ad_gpo_access_control: "enforcing"
          enumerate: false
          cache_credentials: true
          use_fully_qualified_names: true
          fallback_homedir: "/home/%d/%u"
          default_shell: "/bin/bash"
          ad_server: "dc-sssd.ad.sssd.test"
          krb5_server: "dc-sssd.ad.sssd.test"
    host_vars:
      sas-autorid:
        sssd_keytab: "/etc/sssd-test.keytab"
        sssd_id_mapping: "autorid_compat"
        sssd_domain_options:
          access_provider: "ad"
          ad_gpo_access_control: "enforcing"
          enumerate: false
          use_fully_qualified_names: true
          fallback_homedir: "/home/%d/%u"
          default_shell: "/bin/bash"
          ldap_idmap_range_min: 10000
          ldap_idmap_range_max: 60000
          ldap_idmap_range_size: 10000
          ad_server: "dc-sssd.ad.sssd.test"
          krb5_server: "dc-sssd.ad.sssd.test"
  log: true
  playbooks:
    prepare: "../resources/playbooks/prepare.yml"
    converge: "../resources/playbooks/converge.yml"
    verify: "../resources/playbooks/verify.yml"
    side_effect: "../resources/playbooks/side_effect.yml"
  connection_options:
    ansible_user: "molecule"
verifier:
  name: "ansible"
scenario:
  test_sequence:
    - "dependency"
    - "destroy"
    - "syntax"
    - "create"
    - "prepare"
    - "converge"
    - "idempotence"
    - "check"
    - "verify"
    - "side_effect"
    - "destroy"
  name: "default"
platforms:
  - name: "sas-dc"
    hostname: "dc-sssd"
    image: "docker.io/jomrr/molecule-debian:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
    network: "sas-${MOLECULE_SCENARIO_NAME}"
    extra_opts:
      - "--tmpfs=/var/lib/samba:rw,size=1g,mode=0755"
    groups:
      - "sssd_dc"
  - name: "sas-member"
    hostname: "sas-member"
    image: "docker.io/jomrr/molecule-${img:-fedora}:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
    network: "sas-${MOLECULE_SCENARIO_NAME}"
    groups:
      - "sssd_members"
  - name: "sas-autorid"
    hostname: "sas-autorid"
    image: "docker.io/jomrr/molecule-debian:latest"
    pre_build_image: true
    override_command: false
    systemd: "true"
    privileged: true
    network: "sas-${MOLECULE_SCENARIO_NAME}"
    groups:
      - "sssd_members"
